name: Build RPM & Release

on:
  push:
    paths:
      - 'SPECS/**'
      - 'SOURCES/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  job:
    runs-on: ubuntu-latest
    container: fedora:${{ github.ref_name }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          dnf config-manager addrepo --from-repofile=https://developer.download.nvidia.com/compute/cuda/repos/fedora${{ github.ref_name }}/x86_64/cuda-fedora${{ github.ref_name }}.repo
          dnf install -y rpmdevtools

      - name: Build Packages
        run: |
          dnf builddep -y SPECS/*.spec
          spectool --define "_topdir ${GITHUB_WORKSPACE}" --get-files --sourcedir SPECS/*.spec
          rpmbuild --define "_topdir ${GITHUB_WORKSPACE}" -ba SPECS/*.spec

      - name: Prepare Release
        id: vars
        run: |
          echo "version=$(rpmspec -q --qf '%{VERSION}-%{RELEASE}\n' SPECS/*.spec | head -n 1)" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.vars.outputs.version }}
          files: RPMS/*/*
